import os
from datetime import datetime


class MarkdownExporter:

    @staticmethod
    def export(target: str, vulnerabilities: list) -> str:

        os.makedirs("reports", exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = f"reports/report_{timestamp}.md"

        lines = [
            f"# AMPGuard Scan Report",
            f"",
            f"**Target:** `{target}`  ",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
            f"**Total Findings:** {len(vulnerabilities)}",
            f"",
            f"---",
            f"",
            f"## Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
        ]

        for sev in ["Critical", "High", "Medium", "Low"]:
            count = sum(1 for v in vulnerabilities if v.get("severity") == sev)
            lines.append(f"| {sev} | {count} |")

        lines += ["", "---", "", "## Findings", ""]

        for i, v in enumerate(vulnerabilities, 1):
            lines += [
                f"### {i}. {v.get('type', 'Unknown')}",
                f"",
                f"- **Severity:** {v.get('severity', '—')}",
                f"- **URL:** `{v.get('url', '—')}`",
                f"- **Detail:** {v.get('detail', '—')}",
                f"",
            ]

        lines += [
            "---",
            "",
            "*Generated by AMPGuard — for authorized testing only.*",
        ]

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return path